id: td2025
# shareUrl: https://stateofjs.com
questionsUrl: https://surveys.tokyodev.com/en-US/survey/tokyodev/2025
resultsUrl: https://2025.surveys.tokyodev.com/
issuesUrl: https://github.com/tokyodev-inc/tokyodev-devographics/issues/
discordUrl: https://discord.gg/yBGceZ6Swg
year: 2025
status: 2 # preview/open/closed/hidden
resultsStatus: 1 # hidden/preview/published
# imageUrl: https://tokyodev-assets.onrender.com/images/surveys/html2023.png
# faviconUrl: https://devographics.github.io/surveys/state_of_js/js2022/images/js2022-favicon.svg
# socialImageUrl: https://devographics.github.io/surveys/state_of_js/js2022/images/js2022-og.png
enableSkip: true
enableReadingList: false
startedAt: September 5, 2025
endedAt: October 5, 2025
releasedAt: November 21, 2025
hashtag: TokyoDev

faq:
  - tokyodev
  - survey_goals_td2025
  - data_used
  - who_should_take_survey
  - how_long_will_survey_take
  - results_released_td2025

credits:
  - id: michelle_tan
    role: survey_review
  - id: paulo_d_alberti
    role: survey_review
  - id: scott_rothrock
    role: survey_review
  - id: gajo_petrovic
    role: survey_review
  - id: ismael_rekik
    role: survey_review
